### ISSUE TITLE
bug in combat where it will lock up.

### ISSUE THREAD

**Issue by SobieskiCodes** [SobieskiCodes/justpythonthings#6]
not sure where it is, but i'll keep trying to replicate it and print it here.

**Comment by OurSickStory** [comment]
I *do* believe this is fixed. Will try idle a few more times.

**Comment by OurSickStory** [comment]
`You have started a fight with a werewolf. He has 4 health.
-->werewolf missed you!
-->You missed the werewolf!
-->werewolf missed you!
-->You missed the werewolf!
Me:You took 1 damage, you have 9 health left.
Me:You dealt 1 damage, werewolf has 3 health left.
Me:You took 2 damage, you have 7 health left.
-->You missed the werewolf!
Me:You took 1 damage, you have 6 health left.
-->You missed the werewolf!
-->werewolf missed you!
Me:You dealt 1 damage, werewolf has 2 health left.
-->werewolf missed you!
-->You missed the werewolf!
-->werewolf missed you!
-->You missed the werewolf!
Me:You took 1 damage, you have 5 health left.
-->You missed the werewolf!
-->werewolf missed you!
-->You missed the werewolf!
Me:You took 1 damage, you have 4 health left.
-->You missed the werewolf!

=================== RESTART: C:\Users\Owner\Desktop\rpg.py ===================`
